CREATE USER IF NOT EXISTS 'mysql'@'%' IDENTIFIED BY '36L8W7Nm';
GRANT ALL PRIVILEGES ON blog_db.* TO 'mysql'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE TABLE IF NOT EXISTS blog_posts (
    id INT AUTO_INCREMENT PRIMARY KEY,
    Web_Site VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    link VARCHAR(255),
    images TEXT NOT NULL
);